apiVersion: apps/v1

kind: Deployment

metadata:

  name: springboot
  namespace: web

  labels:

    app: springboot
spec:

  replicas: 1

  selector:

    matchLabels:

      app: springboot

  template:

    metadata:

      labels:

        app: springboot
    spec:

      containers:

      - name: springboot

        image: rahulwagh17/kubernetes:jhooq-k8s-springboot


        ports:

        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot
