apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx
  namespace: web

  labels:

    app: nginx
spec:

  replicas: 1

  selector:

    matchLabels:

      app: nginx

  template:

    metadata:

      labels:

        app: nginx
    spec:

      containers:

      - name: nginx

        image: nginx


        ports:

        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nginx
